version: "3.8"
services:
  db:
    image: postgres
    container_name: authdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: authdb
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - finance-management
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - finance-management
    depends_on:
      - db

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  finance-management:
